version: 1

# before:
#   hooks:
#     # You may remove this if you don't use go modules.
#     - go mod tidy
#     # you may remove this if you don't need go generate
#     - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: '386'

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc

brews:
  - name: mmedusa
    folder: .



    # GOARM to specify which 32-bit arm version to use if there are multiple
    # versions from the build section. Brew formulas support only one 32-bit
    # version.
    #
    # Default: 6
    goarm: 6

    # GOAMD64 to specify which amd64 version to use if there are multiple
    # versions from the build section.
    #
    # Default: v1
    goamd64: v1
    url_template: "https://github.com/yuriykuntsyak/{{ .ProjectName }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy

    # Git author used to commit to the repository.
    commit_author:
      name: Yuriy Kuntsyak
      email: yuriykuntsyak@gmail.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    caveats: "How to use this binary"
    homepage: "https://github.com/yuriykuntsyak/mmedusa"
    description: "A tool for managing and deduplicating media files."
    license: "Apache 2.0"
    skip_upload: false
    test: |
      system "#{bin}/mmedusa --help"

    # Repository to push the generated files to.
    repository:
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      owner: yuriykuntsyak
      name: homebrew
      branch: main
