# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmedusa < Formula
  desc "A tool for managing and deduplicating media files."
  homepage "https://github.com/yuriykuntsyak/mmedusa"
  version "0.0.4"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.4/mmedusa_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "35bb9d6bf347ea79966d8029e83e48bba2f8ae5d85e11f94676f2bd1c75acbe8"

      def install
        bin.install "mmedusa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.4/mmedusa_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b615a1784827868046de7f33defc5d4923d321feba748186be8018a950a07d5b"

      def install
        bin.install "mmedusa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.4/mmedusa_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "06ffb65c2fdec6b9619138a6d6c7713c7acf917a651921736ef127e033d23b4f"

      def install
        bin.install "mmedusa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.4/mmedusa_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "6f0f0d5191828a9f0f5cc3c915d5366a004d57dc67498094249d7b4ba003e17c"

      def install
        bin.install "mmedusa"
      end
    end
  end

  head "git@github.com:yuriykuntsyak/mmedusa.git"

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end

  test do
    system "#{bin}/mmedusa --help"
  end
end
