# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmedusa < Formula
    desc "A tool for managing and deduplicating media files."
    homepage "https://github.com/yuriykuntsyak/mmedusa"
    version "0.0.16"
    license "Apache 2.0"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.16/mmedusa_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "db2aa760ec474fd3337baa9a6f49ab8549437c8f8a31fcbc2f5248649e9f0307"
  
        def install
          bin.install "mmedusa"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.16/mmedusa_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "234d22e7429cb35efc1ab2d9e9483f5539a3d81c5a1cff4a86422defd50e2102"
  
        def install
          bin.install "mmedusa"
        end
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.16/mmedusa_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "1037e0a23c197bba28b78fcc25e5e608db84045f2a3545c8f0e1a3b7fd06c703"
  
        def install
          bin.install "mmedusa"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.16/mmedusa_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "c8278b811338f9324fe6706ed3bbe1efab157d88571d7af0d91255a50b3dfbbe"
  
        def install
          bin.install "mmedusa"
        end
      end
    end
  
    def caveats
      <<~EOS
        How to use this binary
      EOS
    end
  
    test do
      system "#{bin}/mmedusa --help"
    end
  end
  